Fix: Build error with vtkh enabled with kokkos HIP with ROCm 7.2.1
When I try to build the rover library, I get these errors:
In file included from <built-in>:1:
In file included from /opt/rocm-7.2.1/lib/llvm/lib/clang/22/include/__clang_hip_runtime_wrapper.h:111:
In file included from /opt/rocm-7.2.1/lib/llvm/lib/clang/22/include/cuda_wrappers/cmath:28:
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/cmath:3699:
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/specfun.h:43:
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:67:
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_iterator.h:85:
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:88:15: error: reference to __host__ function '~Domain' in __host__ __device__ function
   88 |         __location->~_Tp();
      |                      ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:149:12: note: called by '_Destroy<rover::Domain>'
  149 |       std::destroy_at(__pointer);
      |            ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:163:11: note: called by '__destroy<rover::Domain *>'
  163 |             std::_Destroy(std::__addressof(*__first));
      |                  ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:193:35: note: called by '_Destroy<rover::Domain *>'
  193 |         return std::_Destroy_aux<false>::__destroy(__first, __last);
      |                                          ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/alloc_traits.h:948:12: note: called by '_Destroy<rover::Domain *, rover::Domain>'
  948 |       std::_Destroy(__first, __last);
      |            ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:735:7: note: called by '~vector'
  735 |         std::_Destroy(this->_M_impl._M_start, this->_M_impl._M_finish,
      |              ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:733:7: note: called by '~TypedScheduler'
  733 |       ~vector() _GLIBCXX_NOEXCEPT
      |       ^
/home/dev/ascent/src/libs/rover/domain.hpp:28:3: note: '~Domain' declared here
   28 |   ~Domain();
      |   ^

This error occurs because the code is compiled as device code (viskores_add_target_information(rover DEVICE_SOURCES ${rover_sources}) and tries to call destructors, which causes this error.

Fix: Separate the rover source code into device code and host code so that the host code is not compiled on the device.